# Generated by Django 3.2.19 on 2024-05-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0021_auto_20201202_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='due date'),
        ),
    ]
