# Generated by Django 3.2.19 on 2024-05-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20200615_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='due date'),
        ),
    ]
